In [24]:
import numpy as np

In [36]:
# 슬라이싱

array1 = np.arange(start=1,stop=10)
print(array1)
array2 = array1.reshape(3,3)
print(array2[:2,:2])
print('-------------')
print(array2[1:3,0:3])
print('-------------')
print(array2[1:3,:])
print('-------------')
print(array2[:,:])
print('-------------')
print(array2[:2,1:])
print('-------------')
print(array2[:2,0])
print('-------------')
print(array2)

[1 2 3 4 5 6 7 8 9]
[[1 2]
 [4 5]]
-------------
[[4 5 6]
 [7 8 9]]
-------------
[[4 5 6]
 [7 8 9]]
-------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
-------------
[[2 3]
 [5 6]]
-------------
[1 4]
-------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
# 불린 인덱싱

array1 = np.arange(start=1,stop=10)
array3 = array1[array1>5]
bool_indexs = np.array([False,False,False,False,False,True,True,True,True])
array4 = array1[bool_indexs]

print(array1 > 5)
print(array1)
print(array3)
print(array4)

[False False False False False  True  True  True  True]
[1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[6 7 8 9]


In [19]:
# 행렬의 정렬(sort)

org_array = np.array([[3,1,9,5],[1,4,4,2]])
sort_array1 = np.sort(org_array)
sort_array2 = org_array.sort()

print(sort_array2)
print(org_array)
print(sort_array1)

[[0 1 2 3]
 [0 1 2 3]]
None
[[1 3 5 9]
 [1 2 4 4]]
[[1 3 5 9]
 [1 2 4 4]]


In [22]:
# 행렬의 정렬(argsort)

org_array = np.array([[3,1,9,5],[1,4,4,2]])
index_array = np.argsort(org_array)
print(index_array)

[[1 0 3 2]
 [0 3 1 2]]


In [10]:
# 전치행렬(transpose)
arr = np.array([[0,1,2],[3,4,5],[6,7,8]])
arr_ = np.transpose(arr)
print(arr_)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [8]:
# 행렬 곱셈(dot)
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])
C = np.dot(A,B)
print(C)

[[ 58  64]
 [139 154]]
