## Hello Tensorflow
* 버전 설치와 난수 생성하기

In [6]:
print('hello tensorflow')

hello tensorflow


In [1]:
try:
    # %tensorflow_version only exists in Colab.
    %tensorflow_version 2.x
except Exception:
    pass
import tensorflow as tf

In [2]:
tf.debugging.set_log_device_placement(True)

# 텐서 생성
# a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
# b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
# c = tf.matmul(a, b)

# print(c)

Executing op MatMul in device /job:localhost/replica:0/task:0/device:GPU:0
tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)


In [2]:
print(tf.__version__)

2.1.0


In [7]:
rand = tf.random.uniform([1],0,1)
print(rand)
rand2 = tf.random.uniform([4],0,1)
print(rand2)
rand3 = tf.random.uniform([4,4],0,1)
print(rand3)

tf.Tensor([0.5214834], shape=(1,), dtype=float32)
tf.Tensor([0.93029654 0.01592529 0.36988378 0.43143296], shape=(4,), dtype=float32)
tf.Tensor(
[[0.07932186 0.55819654 0.8020581  0.06290126]
 [0.19589877 0.9115809  0.1721952  0.93716407]
 [0.13740516 0.25707078 0.9435084  0.08438718]
 [0.1072582  0.9411864  0.25358105 0.13208377]], shape=(4, 4), dtype=float32)


## 3.3.2 뉴런 만들기

NameError: name '기' is not defined