In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_boston
%matplotlib inline

boston = load_boston()
bostonDF = pd.DataFrame(boston.data,columns=boston.feature_names)
bostonDF['PRICE'] = boston.target
print(bostonDF.head(3))

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   

   PTRATIO       B  LSTAT  PRICE  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  


In [9]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

X_data = bostonDF.drop(['PRICE'],axis=1)
y_data = bostonDF['PRICE']
X_train,X_test,y_train,y_test = train_test_split(X_data,y_data,test_size=0.2,random_state=156)

[-11.422 -24.294 -28.144 -74.599 -28.517]
[3.38  4.929 5.305 8.637 5.34 ]
5.518


In [22]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import cross_val_score

alphas = [0,0.1,1,10,100]
for alpha in alphas:
    ridge = Ridge(alpha=alpha)
    neg_mse_scores = cross_val_score(ridge,X_data,y_data,scoring="neg_mean_squared_error",cv=5)
    rmse_scores = np.sqrt(-1 * neg_mse_scores)
    avg_rmse = np.mean(rmse_scores)

    print("# {}".format(alpha))
    print(np.round(neg_mse_scores,3))
    print(np.round(rmse_scores,3))
    print(round(avg_rmse,3))


# 0
[-12.46  -26.049 -33.074 -80.762 -33.314]
[3.53  5.104 5.751 8.987 5.772]
5.829
# 0.1
[-12.32  -25.198 -32.435 -80.703 -32.88 ]
[3.51  5.02  5.695 8.983 5.734]
5.788
# 1
[-11.711 -23.583 -29.693 -80.23  -31.116]
[3.422 4.856 5.449 8.957 5.578]
5.653
# 10
[-11.422 -24.294 -28.144 -74.599 -28.517]
[3.38  4.929 5.305 8.637 5.34 ]
5.518
# 100
[-12.825 -27.279 -34.68  -52.694 -22.051]
[3.581 5.223 5.889 7.259 4.696]
5.33
